docs - update kind version (#585)
The version requirement was bumped in 3315c2, resulting in the a build
failure when following the documentation.

Current behaviour:
```
$ kne deploy deploy/kne/kind-bridge.yaml
I0105 09:09:28.147208   67772 deploy.go:195] Deploying cluster...
Error: failed to deploy cluster: failed to check for dependencies: kind version check failed: got 0.19.0, want 0.24.0. install with `go install sigs.k8s.io/kind@0.24.0`
```

New behaviour:
```
$ kne deploy deploy/kne/kind-bridge.yaml
I0105 09:13:48.483372   71859 deploy.go:195] Deploying cluster...
I0105 09:13:48.498972   71859 deploy.go:619] kind version valid: got 0.24.0 want 0.24.0
```