deploy - correct go install output (#586)
Upon an invalid `kind` version, the following message is displayed:
Error: failed to deploy cluster: failed to check for dependencies: kind version check failed: got 0.19.0, want 0.24.0. install with `go install sigs.k8s.io/kind@0.24.0`

Executing the instruction fails, due to an in-valid version tag:
`go: sigs.k8s.io/kind@0.24.0: sigs.k8s.io/kind@0.24.0: invalid version: unknown revision 0.24.0`

The `v` is being stripped off by `parseVersion` as changed in 1d152a.

Since `parseVersion` explicitly requires a `v` prefix, it should be safe
to just add this back in the human output.